language: python
matrix:
   include:
       - python: 3.8
         dist: bionic
       - pthon: 3.8 
         arch: arm64
         dist: bionic
         
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5 
  - pypy

install:
  - pip uninstall -y nose
  - pip install -r requirements.txt --use-mirrors
script:
  - python setup.py build_tests || python setup.py egg_info; python selftest.py
